{
  "formatVersion": "1.1",
  "component": {
    "group": "v.akfz",
    "module": "aslib-fabric",
    "version": "Dev_1.20.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aslib-fabric-Dev_1.20.1-SNAPSHOT.jar",
          "url": "aslib-fabric-Dev_1.20.1-SNAPSHOT.jar",
          "size": 276831,
          "sha512": "3e44f84e471523906d95be556e63458e85001c94c9e5d99301a7d2a444abcb5147d58145f94391d685438c174b5fbe550397ed6193f0d6118309711b6a52648d",
          "sha256": "aa679194d91f76d262c1de5de8b45084c005f27a9a7453c13e3ca35b41409789",
          "sha1": "2bd3aa99408e37639a8e0ba8c4d5be4fd33bf8ba",
          "md5": "e338e22fdd9277cc6fe495380a337842"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "v.akfz",
          "module": "aslib-fabric",
          "version": {
            "requires": "Dev_1.20.1-SNAPSHOT"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.1-47.4.20_mapped_parchment_2023.09.03-1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "aslib-fabric-Dev_1.20.1-SNAPSHOT.jar",
          "url": "aslib-fabric-Dev_1.20.1-SNAPSHOT.jar",
          "size": 276831,
          "sha512": "3e44f84e471523906d95be556e63458e85001c94c9e5d99301a7d2a444abcb5147d58145f94391d685438c174b5fbe550397ed6193f0d6118309711b6a52648d",
          "sha256": "aa679194d91f76d262c1de5de8b45084c005f27a9a7453c13e3ca35b41409789",
          "sha1": "2bd3aa99408e37639a8e0ba8c4d5be4fd33bf8ba",
          "md5": "e338e22fdd9277cc6fe495380a337842"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aslib-fabric-Dev_1.20.1-SNAPSHOT-sources.jar",
          "url": "aslib-fabric-Dev_1.20.1-SNAPSHOT-sources.jar",
          "size": 139195,
          "sha512": "61f4d7ae2418dd1f0410efe946da0969774271f668cf931afa8af3e8c895f65e48517b12b0961b6d5f61660d3845da78d7a9faa62e8841978bea272e6e21b8da",
          "sha256": "acec85133ce41f8751a5367580e8ba0f59dcdbf362cdf703a356f5bba871b988",
          "sha1": "372ab2cff5996d16c9361a5f89cfffaa9b41f2e9",
          "md5": "5588b49c11cd5eb31617fe5f9162e76b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aslib-fabric-Dev_1.20.1-SNAPSHOT-javadoc.jar",
          "url": "aslib-fabric-Dev_1.20.1-SNAPSHOT-javadoc.jar",
          "size": 708751,
          "sha512": "0df33af5a729664b0efd339cb77125c28091457a11ad9bd2919ce7563512cad23ccd455f038b7a0fa5830ba32cb031f0e2127288bbcde300e787f0adcf2927fe",
          "sha256": "31f9033083530be6b262ce1f4968805f7045aa6115a9027eb35383db9514de8e",
          "sha1": "d58500300b345b23f74971153784f3caa264a959",
          "md5": "b8830bf8bf35855832ddb968e5b93f2e"
        }
      ]
    }
  ]
}
