{
  "formatVersion": "1.1",
  "component": {
    "group": "v.akfz",
    "module": "aslib-fabric",
    "version": "Dev_1.20.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aslib-fabric-Dev_1.20.1-SNAPSHOT.jar",
          "url": "aslib-fabric-Dev_1.20.1-SNAPSHOT.jar",
          "size": 282237,
          "sha512": "71fb7f192684e8f79e5780ed45efbe39b254b600b107deda04e9235ba1197f81ffe839af0aa0aa35cdbee9d6d18fe1a3bb61e923fb447ea4722fa1756cd24aeb",
          "sha256": "9cbcc32f641e6212f14a72ceb65949675146b906e75a2c6cd2e854a3ca23558e",
          "sha1": "1207453e15e520dba736a99922c53ece0025b962",
          "md5": "0ab38d93ea7957b7b1c2c33dc4c31eee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "v.akfz",
          "module": "aslib-common",
          "version": {
            "requires": "Dev_1.20.1-SNAPSHOT"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        }
      ],
      "files": [
        {
          "name": "aslib-fabric-Dev_1.20.1-SNAPSHOT.jar",
          "url": "aslib-fabric-Dev_1.20.1-SNAPSHOT.jar",
          "size": 282237,
          "sha512": "71fb7f192684e8f79e5780ed45efbe39b254b600b107deda04e9235ba1197f81ffe839af0aa0aa35cdbee9d6d18fe1a3bb61e923fb447ea4722fa1756cd24aeb",
          "sha256": "9cbcc32f641e6212f14a72ceb65949675146b906e75a2c6cd2e854a3ca23558e",
          "sha1": "1207453e15e520dba736a99922c53ece0025b962",
          "md5": "0ab38d93ea7957b7b1c2c33dc4c31eee"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aslib-fabric-Dev_1.20.1-SNAPSHOT-sources.jar",
          "url": "aslib-fabric-Dev_1.20.1-SNAPSHOT-sources.jar",
          "size": 146078,
          "sha512": "8bea8c35c258947d0022bdb1167e8e65ad146d53c796febf4e0bcd2ad5898ca4aa01b613bafe7aa53c1d070611f617ee50fef197ab7c2d03fd89339d0ca33960",
          "sha256": "11df2226fe59d0545e38f4c8fc3e281a05c5e902bdbc65d942c0d50c1fe98866",
          "sha1": "75b81d886cf9573929492e062db543061ebe1a0e",
          "md5": "5a15e65a3ef51fdcdd827978e5c398d1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aslib-fabric-Dev_1.20.1-SNAPSHOT-javadoc.jar",
          "url": "aslib-fabric-Dev_1.20.1-SNAPSHOT-javadoc.jar",
          "size": 708823,
          "sha512": "eb6a09088eb9f961be69879497845c3dd8589ab8d85029ed288863b7c54458740373edfb7d56a71940b82d4369ca83dc9ee3e80455674f27af83d8011ba28cb4",
          "sha256": "1642ccb1be9e173b74e67c9cf3e8e64dea48d69853b0bfc05ce14ce1d5994f25",
          "sha1": "bc11ce0809a21a263d2bb39fbd1f61a86d3978c9",
          "md5": "485730f071f7eebd0af9f3650232981e"
        }
      ]
    }
  ]
}
