modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="aslib"
version="1"
displayName="AsLib"
logoFile="icon.png"
authors="Akaize, SweetB1ans"
description="""
something genially"""

[[dependencies.aslib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.aslib]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

