package v.akfz.aslib.datagen.lang;

import net.minecraft.resources.ResourceLocation;
import org.jetbrains.annotations.Nullable;
import v.akfz.aslib.datagen.api.Serializable;

import java.nio.file.Path;
import java.util.*;

public class LangData implements Serializable<String> {
	private final String namespace;
	private final String languageCode;
	private final Map<String, String> translations = new LinkedHashMap<>();
	private final List<String> header = new ArrayList<>();

	public LangData(String namespace, String languageCode) {
		this.namespace = namespace;
		this.languageCode = languageCode;
	}

	public LangData(String namespace) {
		this(namespace, "en_us");
	}

	public LangData add(String key, String value) {
		if (key != null && value != null) {
			this.translations.put(key, value);
		}
		return this;
	}

	public LangData addHeaderComment(String comment) {
		this.header.add("# " + comment);
		return this;
	}

	public LangData addDefaultHeader() {
		this.header.add("Generated by ASLib Data Generator");
		this.header.add("Namespace: " + namespace);
		this.header.add("Language: " + languageCode);
		this.header.add("");
		return this;
	}

	@Override
	public @Nullable ResourceLocation getRLPath() {
		return new ResourceLocation(namespace, "lang/" + languageCode);
	}

	@Override
	public @Nullable Path getPath() {
		return null;
	}

	@Override
	public boolean isAsset() {
		return true;
	}

	@Override
	public String getExtension() {
		return "lang";
	}

	@Override
	public boolean isSystem() {
		return false;
	}

	@Override
	public String serialize() {
		StringBuilder sb = new StringBuilder();

		if (!header.isEmpty()) {
			for (String comment : header) {
				sb.append(comment).append("\n");
			}
			sb.append("\n");
		}

		TreeMap<String, String> sortedTranslations = new TreeMap<>(translations);
		for (Map.Entry<String, String> entry : sortedTranslations.entrySet()) {
			sb.append(entry.getKey()).append("=").append(entry.getValue()).append("\n");
		}

		return sb.toString();
	}
}