buildscript {
    repositories {
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
    }
    dependencies {
        classpath "org.spongepowered:mixingradle:${project.mixingradle_version}"
    }
}

allprojects {
    apply plugin: 'java'

    java {
        toolchain.languageVersion = JavaLanguageVersion.of(17)
    }

    version = project.mod_version
    group = project.maven_group
}

subprojects {
    tasks.withType(JavaCompile).configureEach {
        it.options.encoding = 'UTF-8'
        it.options.release = 17
    }

    if (project.name != 'common') {
        configurations {
            embed
            implementation.extendsFrom(embed)
        }

        tasks.named('jar', Jar).configure {
            duplicatesStrategy = DuplicatesStrategy.EXCLUDE

            from {
                configurations.embed.collect { it.isDirectory() ? it : zipTree(it) }
            }

            destinationDirectory.set(file("${rootProject.layout.buildDirectory.get().asFile}/libs"))
            archiveFileName = "${project.name}-${project.version}-dev.jar"

            if (file("LICENSE").exists()) {
                from("LICENSE") {
                    rename { "${it}_${project.base.archivesName.get()}" }
                }
            }
        }

        tasks.named('processResources', ProcessResources).configure {
            duplicatesStrategy = DuplicatesStrategy.INCLUDE

            if (project.name == 'forge') {
                exclude 'fabric.mod.json'
                exclude 'quilt.mod.json'
            }

            if (project.name == 'neoforge') {
                exclude 'fabric.mod.json'
                exclude 'quilt.mod.json'
            }

            if (project.name == 'fabric') {
                exclude 'META-INF/mods.toml'
                exclude 'quilt.mod.json'
                exclude 'pack.mcmeta'
            }
        }
    }
}