import org.objectweb.asm.ClassReader
import org.objectweb.asm.tree.ClassNode

buildscript {
    repositories {
        mavenCentral()
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
    }
    dependencies {
        classpath "org.spongepowered:mixingradle:${project.mixingradle_version}"
    }
}

allprojects {
    apply plugin: 'java'

    java {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    version = project.mod_version
    group = project.maven_group
}

subprojects {
    tasks.processResources {
        duplicatesStrategy = DuplicatesStrategy.INCLUDE
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.encoding = 'UTF-8'
        it.options.release = 17
    }

    afterEvaluate {
        def finalJarName = "${rootProject.archives_base_name}-${project.name}-${project.version}.jar"

        if (project.name != 'common') {
            configurations {
                embed
                implementation.extendsFrom(embed)
            }

            if (project.name == 'fabric') {
                tasks.named('remapJar') { task ->
                    task.archiveFileName = finalJarName
                    task.from {
                        configurations.embed.collect { it.isDirectory() ? it : zipTree(it) }
                    }

                    if (file("LICENSE").exists()) {
                        task.from("LICENSE") {
                            rename { "${it}_${project.base.archivesName.get()}" }
                        }
                    }
                }
            } else {
                tasks.named('jar', Jar) { Jar task ->
                    task.duplicatesStrategy = DuplicatesStrategy.EXCLUDE
                    task.destinationDirectory.set(layout.buildDirectory.dir("libs"))
                    task.archiveFileName = finalJarName

                    task.from {
                        configurations.embed.collect { it.isDirectory() ? it : zipTree(it) }
                    }

                    if (file("LICENSE").exists()) {
                        task.from("LICENSE") {
                            rename { "${it}_${project.base.archivesName.get()}" }
                        }
                    }
                }
            }

            tasks.named('processResources', ProcessResources).configure {
                duplicatesStrategy = DuplicatesStrategy.INCLUDE

                if (project.name == 'forge') {
                    exclude 'fabric.mod.json'
                }

                if (project.name == 'neoforge') {
                    exclude 'fabric.mod.json'
                    exclude 'quilt.mod.json'
                }

                if (project.name == 'fabric') {
                    exclude 'META-INF/mods.toml'
                    exclude 'pack.mcmeta'
                }
            }
        } else {
            tasks.named('jar', Jar) { Jar task ->
                task.duplicatesStrategy = DuplicatesStrategy.EXCLUDE
                task.archiveFileName = finalJarName
            }
        }
    }

    tasks.withType(Jar).configureEach {
        def targetAnnotation = "Ln/paradox/aslib/annotation/DontCompile;"

        eachFile { fileCopyDetails ->
            if (fileCopyDetails.name.endsWith('.class')) {
                def file = fileCopyDetails.file

                if (file.exists()) {
                    def inputStream = file.newInputStream()
                    try {
                        def reader = new ClassReader(inputStream)
                        def classNode = new ClassNode()
                        reader.accept(classNode, ClassReader.SKIP_CODE | ClassReader.SKIP_DEBUG | ClassReader.SKIP_FRAMES)

                        def hasAnnotation = classNode.invisibleAnnotations?.any { it.desc == targetAnnotation } ||
                                classNode.visibleAnnotations?.any { it.desc == targetAnnotation }

                        if (hasAnnotation) {
                            fileCopyDetails.exclude()
                            logger.lifecycle("[AsLib Build] [${project.name}] Класс ${classNode.name} успешно удален из релиза (@DontCompile)")
                        }
                    } catch (Exception e) {
                    } finally {
                        inputStream.close()
                    }
                }
            }
        }
    }
}

tasks.register('compileAll', Copy) {
    group = 'build'
    description = 'Compile and copy from all subprojects JAR in main build/libs'

    subprojects.each { subproject ->
        if (subproject.name == 'fabric') {
            dependsOn subproject.tasks.matching { it.name == 'remapJar' }
        } else {
            dependsOn subproject.tasks.matching { it.name == 'jar' }
        }
    }

    subprojects.each { subproject ->
        if (subproject.name == 'common') {
            from(subproject.layout.buildDirectory.dir("devlibs")) {
                include "*.jar"
            }
        } else {
            from(subproject.layout.buildDirectory.dir("libs")) {
                include "*.jar"
            }
        }
    }

    into(layout.buildDirectory.dir("libs"))

    outputs.upToDateWhen { false }
}