{
  "formatVersion": "1.1",
  "component": {
    "group": "v.akfz",
    "module": "aslib-common",
    "version": "Dev_1.20.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aslib-common-Dev_1.20.1-SNAPSHOT.jar",
          "url": "aslib-common-Dev_1.20.1-SNAPSHOT.jar",
          "size": 282373,
          "sha512": "c08e0e318a215cfc3add82d2aa45c48085dabc6fa82d682407a909c9d52c30ca4cbd92972eb0f1dba10395f3f40db3c0993892495f7d3820087ab4270bc76990",
          "sha256": "a09b74c35e8388027f07b1c6ce2ee9ffb93288fbc62c63ab91fb97a14a6cd6bd",
          "sha1": "4c24fac4e65c5490dcb39141153d21b2ed49a85f",
          "md5": "1e7ed9f27d09787bd2ae73db60b5b3c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aslib-common-Dev_1.20.1-SNAPSHOT.jar",
          "url": "aslib-common-Dev_1.20.1-SNAPSHOT.jar",
          "size": 282373,
          "sha512": "c08e0e318a215cfc3add82d2aa45c48085dabc6fa82d682407a909c9d52c30ca4cbd92972eb0f1dba10395f3f40db3c0993892495f7d3820087ab4270bc76990",
          "sha256": "a09b74c35e8388027f07b1c6ce2ee9ffb93288fbc62c63ab91fb97a14a6cd6bd",
          "sha1": "4c24fac4e65c5490dcb39141153d21b2ed49a85f",
          "md5": "1e7ed9f27d09787bd2ae73db60b5b3c9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aslib-common-Dev_1.20.1-SNAPSHOT-sources.jar",
          "url": "aslib-common-Dev_1.20.1-SNAPSHOT-sources.jar",
          "size": 146059,
          "sha512": "9b2ce79d33a901f6330098d998300feccfc32a15a69e4ded976ce18a1e4cefc9c15a6ea55e761ecf2e4e6b53279e43df3e1f48a963fd80b9e71fc8f10d3e83c3",
          "sha256": "c910944af395ae93a410d515fa042663403f0c67593e44b4a518b50e9e3cbb34",
          "sha1": "854c298473d164404afdde72fd974c872f1c6934",
          "md5": "14fc5c77cd793663bc84d0e0a810ecca"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aslib-common-Dev_1.20.1-SNAPSHOT-javadoc.jar",
          "url": "aslib-common-Dev_1.20.1-SNAPSHOT-javadoc.jar",
          "size": 709115,
          "sha512": "8c933241c7e28d43db32d161d7e8ce1bbcab44bd90af35cfcc90b50f10ef3b8fa52147f49c9a8a962dfb4802c15feb745887068b08ae10351a13406bbedefcaa",
          "sha256": "fcd8f777db7c2c3be7ba312a13bcac9cb3b43944930aa6f6721fc3f3e7d83426",
          "sha1": "4c3cb63e6bcbc6afb8cb28f724c2d6a815b31e43",
          "md5": "23b94006c5feb78d46677c4a44e37fb4"
        }
      ]
    }
  ]
}
