{
  "formatVersion": "1.1",
  "component": {
    "group": "v.akfz",
    "module": "aslib-common",
    "version": "Dev_1.20.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aslib-common-Dev_1.20.1-SNAPSHOT.jar",
          "url": "aslib-common-Dev_1.20.1-SNAPSHOT.jar",
          "size": 282373,
          "sha512": "c08e0e318a215cfc3add82d2aa45c48085dabc6fa82d682407a909c9d52c30ca4cbd92972eb0f1dba10395f3f40db3c0993892495f7d3820087ab4270bc76990",
          "sha256": "a09b74c35e8388027f07b1c6ce2ee9ffb93288fbc62c63ab91fb97a14a6cd6bd",
          "sha1": "4c24fac4e65c5490dcb39141153d21b2ed49a85f",
          "md5": "1e7ed9f27d09787bd2ae73db60b5b3c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aslib-common-Dev_1.20.1-SNAPSHOT.jar",
          "url": "aslib-common-Dev_1.20.1-SNAPSHOT.jar",
          "size": 282373,
          "sha512": "c08e0e318a215cfc3add82d2aa45c48085dabc6fa82d682407a909c9d52c30ca4cbd92972eb0f1dba10395f3f40db3c0993892495f7d3820087ab4270bc76990",
          "sha256": "a09b74c35e8388027f07b1c6ce2ee9ffb93288fbc62c63ab91fb97a14a6cd6bd",
          "sha1": "4c24fac4e65c5490dcb39141153d21b2ed49a85f",
          "md5": "1e7ed9f27d09787bd2ae73db60b5b3c9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aslib-common-Dev_1.20.1-SNAPSHOT-sources.jar",
          "url": "aslib-common-Dev_1.20.1-SNAPSHOT-sources.jar",
          "size": 146059,
          "sha512": "09565fbd1c1b6ebb6f3c86a2d4b788603d8368d739b800880c3d082578864277a0283671ea3bde325285b2291bf66d210dd90a842a5235cd1e56c99a496a78d9",
          "sha256": "a19058cffe3df92f3d309c4b12f62c082df401992a4b322d4ba9dfe5acaf0703",
          "sha1": "a941734ed68c4f65d1a4b5cfb6cf04d921cb3f70",
          "md5": "9c3bcca179e26483faf30fbdf5c65930"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aslib-common-Dev_1.20.1-SNAPSHOT-javadoc.jar",
          "url": "aslib-common-Dev_1.20.1-SNAPSHOT-javadoc.jar",
          "size": 709115,
          "sha512": "9943454531653b77a60e4f67e7e59c8c9f6b8cdd5333bb986918e1d4998f981c8a33f5d50dd5278866a4cd9331425a44eece2681cae362d2a6213b36fecd04dc",
          "sha256": "fa4aa6e64174b3a9451d60c4246764b9fbec5af7db680d9ca5f5076089664d76",
          "sha1": "4f48325a78ffb8775c853c8040e8a48652eb1be1",
          "md5": "7e9572a5e8f75ef05a2bb66c3a5c7583"
        }
      ]
    }
  ]
}
