{
  "formatVersion": "1.1",
  "component": {
    "group": "v.akfz",
    "module": "aslib-common",
    "version": "Dev_1.20.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aslib-common-Dev_1.20.1-SNAPSHOT.jar",
          "url": "aslib-common-Dev_1.20.1-SNAPSHOT.jar",
          "size": 282373,
          "sha512": "c08e0e318a215cfc3add82d2aa45c48085dabc6fa82d682407a909c9d52c30ca4cbd92972eb0f1dba10395f3f40db3c0993892495f7d3820087ab4270bc76990",
          "sha256": "a09b74c35e8388027f07b1c6ce2ee9ffb93288fbc62c63ab91fb97a14a6cd6bd",
          "sha1": "4c24fac4e65c5490dcb39141153d21b2ed49a85f",
          "md5": "1e7ed9f27d09787bd2ae73db60b5b3c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aslib-common-Dev_1.20.1-SNAPSHOT.jar",
          "url": "aslib-common-Dev_1.20.1-SNAPSHOT.jar",
          "size": 282373,
          "sha512": "c08e0e318a215cfc3add82d2aa45c48085dabc6fa82d682407a909c9d52c30ca4cbd92972eb0f1dba10395f3f40db3c0993892495f7d3820087ab4270bc76990",
          "sha256": "a09b74c35e8388027f07b1c6ce2ee9ffb93288fbc62c63ab91fb97a14a6cd6bd",
          "sha1": "4c24fac4e65c5490dcb39141153d21b2ed49a85f",
          "md5": "1e7ed9f27d09787bd2ae73db60b5b3c9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aslib-common-Dev_1.20.1-SNAPSHOT-sources.jar",
          "url": "aslib-common-Dev_1.20.1-SNAPSHOT-sources.jar",
          "size": 146059,
          "sha512": "a38df0fbb4077883824470449b1274ac44d8e0f89a9333cd00a261cdbe56c8345a45fbc7ba2922e407ceb5fc0c001f38b0c764881622d5104fefc4b3bc55bf24",
          "sha256": "17365ec85c52663455ea5f72ec63a92b80e98915136982e20ba247ac9e650604",
          "sha1": "570b0ff8ad0f05b9f45ae88ecf3b110b53ad66df",
          "md5": "9dc83f699cd3ea8a27a7026fea1a88b6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aslib-common-Dev_1.20.1-SNAPSHOT-javadoc.jar",
          "url": "aslib-common-Dev_1.20.1-SNAPSHOT-javadoc.jar",
          "size": 709115,
          "sha512": "98fc61daf3e3d7c39f8db848b54fa80f9b493b372942c915a4efba1edc41f9857049a0b794cec4ffb22d06976e9dccb7ef95673e2e74b531bb8a30709ed8bac5",
          "sha256": "d97fc8965ba1562fe0a75f5b197c434a2f8b0a58396dafbfdb81e07259fe7060",
          "sha1": "955a04e76ded5d24d6968d8fd19e99530358823b",
          "md5": "9db181e0897ca072c7c8ce94690002dd"
        }
      ]
    }
  ]
}
